### PR TITLE
Restrict video link workaround to Discord&Telegram

### PR DESCRIPTION
**Pull request by sfan5**
38c9a3c8cf0384f1f9d8e2e8c6af8d1e15e9f2b1 removed this check previously

### CODE REVIEW

**Comment by dangeredwolf** [comment]
Does this workaround cause broken behaviors in other apps?

**Comment by sfan5** [comment]
Not that I'm aware of, but for unaffected apps this indirection is unnecessary (or worse visually distracting if the link gets displayed).

**Comment by dangeredwolf** [comment]
Are there actually any apps that display the video URL?

**Comment by sfan5** [comment]
The "app" in this case is an IRC bot that relies on fxtwitter.

**Pull request merged**
